// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy5foUFwTIdLfR__Q0ZIIzO3G4zojbxDs',
    appId: '1:522327777003:web:3bad1e2ab74625665fa8ae',
    messagingSenderId: '522327777003',
    projectId: 'flutter-a4eca',
    authDomain: 'flutter-a4eca.firebaseapp.com',
    storageBucket: 'flutter-a4eca.appspot.com',
    measurementId: 'G-4HBGC5SVS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAccNaogmsEHCg0OFaVCRn0ctYoYNvlCg',
    appId: '1:522327777003:android:77ae4f11f92c71d95fa8ae',
    messagingSenderId: '522327777003',
    projectId: 'flutter-a4eca',
    storageBucket: 'flutter-a4eca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDttxX_xAhRkEjlT0Te2yCrNMMmd42SjJ8',
    appId: '1:522327777003:ios:0c181a8f40f5be6a5fa8ae',
    messagingSenderId: '522327777003',
    projectId: 'flutter-a4eca',
    storageBucket: 'flutter-a4eca.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDttxX_xAhRkEjlT0Te2yCrNMMmd42SjJ8',
    appId: '1:522327777003:ios:f7a0a18754fd1dad5fa8ae',
    messagingSenderId: '522327777003',
    projectId: 'flutter-a4eca',
    storageBucket: 'flutter-a4eca.appspot.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
